### PR TITLE
Add thread support, fix bugs, improve code, Docker and pipenv support, relicense to AGPL

### PR DESCRIPTION
**Pull request by JonathanFeenstra**
This PR:
- adds thread support (closes issue #18)
- fixes bugs when using certain commands in DMs
- adds support for [uvloop](https://github.com/MagicStack/uvloop) on Linux and macOS
- allows the bot to be installed using Docker or pipenv
- adds a new `core` module for code used in multiple cogs (in favour of putting everything in the `QuoteBot` class)
- splits the `Main` cog into `quote` and `settings`
- adds `credentials.json.example` so the real credentials can be added to .gitignore
- adds type hints to all method signatures
- improves overall code quality
- relicenses the project to AGPL-3.0

Note that it requires Python 3.9, discord.py 2.0.0a (master branch of the archived discord.py repo) and more changes in the structure of the SQLite database before updating existing instances of the bot.

### CODE REVIEW

**Comment by Deivedux** [comment]
Is this ready for merge? Any more commits?

**Comment by JonathanFeenstra** [comment]
@Deivedux These are my final changes for this PR. For accountability, it would be best if you and @kageroukw mark this PR as approved, to confirm you agree with the relicensing.

**Comment by JonathanFeenstra** [comment]
Oops, forgot an import. These should actually be the last commits though

**Review by ghost — APPROVED** [review]

**Review by Deivedux — APPROVED** [review]

**Comment by ghost** [comment]
Looks good. Fire away.

**Pull request merged**
