### PR TITLE
implemented aiosqlite database and refactored code

### PR DESCRIPTION
**Pull request by JonathanFeenstra**
I think using `aiosqlite` would be the most straightforward way to prevent deadlocks when using SQLite asynchronously. I would recommend taking care of the dependencies in the installer script instead of including them directly in the repository, therefore I removed the files that were copied from `discord.py`.

### CODE REVIEW

**Review by Deivedux — DISMISSED** [review]
As much as I don't like too much change, I'll have to agree with you, and also thanks to you for showing how to implement the `aiosqlite`. But I have some problems with this.

There are well-thought-out reasons why I decided to include the discord folder as well rather than installing it normally. I don't trust the users, nor myself to keep the future stable build up-to-date to keep up with new discord.py versions. If the user installs a newer version of discord.py with changes that aren't currently included in Quote, then it's basically on me for not keeping my code up-to-date. Though, I'd rather not have to update and restart the Quote bot for these kinds of unnecessary reasons.

Also, I appreciate your way of indenting, but I'd also appreciate if it wouldn't also force me to change my code writing habits to keep up with future changes in the code. Thanks.

**Comment by ghost** [comment]
Need another review, now that we've gone over the points on Discord.
List of matters discussed to be attached as well, in a bulleted list form, with the corresponding lines of code (Example: `[L#001](https://...)` for clarification for any new comers from the web.


Example being:

Review Breakdown:
- [L#33](https://github.com/Quote-Bot/QuoteBot) - _This was discussed like this, because this._

**Review by Deivedux — APPROVED** [review]
I personally don't have any further issues with this, as long as everything works. Will take some time to adapt to this big change.

**Comment by JonathanFeenstra** [comment]
> List of matters discussed to be attached as well, in a bulleted list form, with the corresponding lines of code (Example: `[L#001](https://...)` for clarification for any new comers from the web.
> 
> Example being:
> 
> Review Breakdown:
> 
>     * [L#33](https://github.com/Quote-Bot/QuoteBot) - _This was discussed like this, because this._

Summary of changes (given the large amount of code changed, the specific lines are not mentioned):
* Replaced `DBService.py` with an `aiosqlite`-based system in `db_service.py`
* Changed database table and column names to `snake_case` for case-insensitive word separation
* Refactored all database interactions to work with the new system and replaced insecure string formatting with DB-API's parameter substitution
* Removed files that were copied over from `discord.py` in favour of installation of dependencies in the launcher scripts (specific versions can still be specified) 
* Replaced tab-indents with spaces to comply with PEP 8
* Implemented custom `QuoteBot` class to make the configuration, database and localisations accessible as attributes in all cogs without needing to import from the `Main` cog
* Fixed `Botlog` cog to produce the correct messages in the configured webhook
* Added `.gitignore` to prevent `__pycache__` folders and the SQLite database from being included in the repository

**Pull request merged**
